language: crystal

# Uncomment the following if you'd like Travis to run specs and check code formatting
# script:
#   - crystal spec
#   - crystal tool format --check
addons:
  apt:
    packages:
      - gcc
      - pkg-config
      - git
      - tzdata
      - libpcre3-dev
      - libevent-dev
      - libyaml-dev
      - libgmp-dev
      - libssl-dev
      - libxml2-dev
