db:
  user: kemal
  password: kemal
  host: localhost
  port: 5432
  dbname: discovery
auth0:
  # no trailing slash
  domain: ""
  # called "client id" in dashboard
  pubkey: ""
  # keep private!!!
  privkey: ""
hostname: ""
secret: ""